### ISSUE TITLE
I customized ables in vue2.0 and never displayed them. I don't know why

### ISSUE THREAD

**Issue by w934423231** [probil/vue-moveable#317]
`  ables: {
        name: "mouseTest",
        props: {},
        events: {},
        render(moveable, React) {
          const CustomElement = moveable.useCSS(
            "div",
            `
        {
            position: absolute;
        }
        `
          );
          // Add key (required)
          // Add class prefix moveable-(required)
          return moveable.createElement("div", {}, "lietu");
        },
        mouseEnter() {
          console.log("ENTER");
        },
        mouseLeave() {
          console.log("LEAVE");
        }
      },`
这是我在 vue data中定义的组件数据

**Comment by UILKUNP** [comment]
## solved this by queryElement
## looks like this
![image](https://user-images.githubusercontent.com/48908684/136877226-94bcb20b-0076-425e-ab73-c7aeb4a95c50.png)

### js
```js
this.$nextTick(() => {
  // query bottom button
  const sButton = document.querySelector('div[data-direction="s"]');
  // insert Html
  sButton.innerHTML = `<div class="double">双击修改文字<div>`;
  const effect=this.doSomething;
  // query inserted and addEventListener
  document.querySelector(".double").addEventListener( "touchend", effect );
});
```
### css
```css
.double {
  width: 200px;
  text-align: center;
  height: 60px;
  line-height: 60px;
  border-radius: 10px;
  position: absolute;
  bottom: -70px;
  background: rgba(#000, 0.8);
  color: #fff;
  left: 50%;
  transform: translateX(-50%);
  font-size: 0.8rem;
}

```
