### ISSUE TITLE
How to set initial coordinates / size? 

### ISSUE THREAD

**Issue by msurguy** [probil/vue-moveable#32]
Hello and thank you for this library! 

I'd like to initialize the component with specific size / location. Is it possible?

**Comment by probil** [comment]
Hi @msurguy 👋 

There is no convenient, Vue-way of doing it right now

But you can always do it in css. :)
```css
.moveable {  /* container should be relative */
    position: absolute;

    /* initial size */
    width: 150px;  
    height: 150px;

    /* initial position */
    left: 125px;
    top: 140px;
}
```
